### ISSUE TITLE
Pointer on validation

### ISSUE THREAD

**Issue by technomage** [emberjs-addons/ember-bootstrap#11]
I could use a pointer on how validation is intended to work.  You reference bindingContext on the parent view (Bootstrap.TextField for example), and then look for isValid and errors on that object.  Is bindingContext something you invented or part of ember?  Do I create bindingContextBinding to point to the object that does the validation (the controller)?

**Comment by dmathieu** [comment]
bindingContext is(/was?) part of ember.
It returns the context around which the binding is happening (basically, the controller).

However, this is more of a hack in order to get basic error management in models.
It will have to be refactored with emberjs/data#268
