### ISSUE TITLE
Considering a gemspec for this

### ISSUE THREAD

**Issue by yaoquan** [emberjs-addons/ember-bootstrap#23]
Are you considering to add gemspec to this?

**Comment by bradleypriest** [comment]
@yaoquan This is just the Javascript repository. Generally if a rubygem is released to integrate a JS library it is done as a separate project.

**Comment by yaoquan** [comment]
Alright. Thanks for going through that with me. Thanks for the work on this. Will be using it.

**Comment by dmathieu** [comment]
Agreed with @bradleypriest. There isn't only ruby (and not only rails either).
