### ISSUE TITLE
What is the correct way to build this add-on?

### ISSUE THREAD

**Issue by ulisesrmzroche** [emberjs-addons/ember-bootstrap#29]
I haven't had much luck finding out how to use this with my ember app. What is the correct way to instal/use this add-on?

**Comment by jakehow** [comment]
@ulisesrmzroche I am pretty sure it is a rails gem meant to be used in the asset-pipeline

add it to the Gemfile, then add 

//= require ember-bootstrap

to zipmark.js and see if that works

**Comment by jakehow** [comment]
also, order matters in zipmark.js so play around with that

**Comment by dmathieu** [comment]
Sorry, I didn't see this issue.
No, ember-bootstrap is not a rails gem. You can use it with any backend.

You can download the latest version in the [download page](https://github.com/emberjs-addons/ember-bootstrap/downloads).
Add it to your javascript assets. It needs to be loaded after Ember.
