### ISSUE TITLE
Download Links broken

### ISSUE THREAD

**Issue by patdohere** [emberjs-addons/ember-bootstrap#30]
Hi,

Ember-bootstrap download links are broken.

**Comment by dmathieu** [comment]
What links ?
The [GitHub downloads](https://github.com/emberjs-addons/ember-bootstrap/downloads) exist, and they work (though it's not the latest version).

**Comment by patdohere** [comment]
I get a file not found on github?

**Comment by dmathieu** [comment]
It seems the files were lost by github when the repository was moved. I've filed a bug request with them about this.

**Comment by dmathieu** [comment]
github confirms the issue. I just uploaded the files again :
https://github.com/emberjs-addons/ember-bootstrap/downloads
