### ISSUE TITLE
Should README be updated to remove Bootstrap.Button?

### ISSUE THREAD

**Issue by mikegrassotti** [emberjs-addons/ember-bootstrap#39]
Seems like Bootstrap.Button was removed in this commit:

https://github.com/emberjs-addons/ember-bootstrap/commit/b04c9ce21ffca450a636b0d5a37a191dabd3b44a

but it's the first example listed in the README.

**Comment by dmathieu** [comment]
Yes, because `Ember.Button` has been deprecated in favor of `{{action}}`.
Thank you !
