### ISSUE TITLE
Assign classes to children

### ISSUE THREAD

**Issue by ghost** [emberjs-addons/ember-bootstrap#42]
E.g. make form element labels and inputs have an additional class of "span12" when the grid system is fluid. Or is their a workaround?

**Comment by bradleypriest** [comment]
@kelonye Can you please explain what you need to do this for? Are you adding "row-fluid" to the control-group?

**Comment by ghost** [comment]
@bradleypriest, was doing this http://goo.gl/HLyAs which isn't great, made [this](https://github.com/emberjs-addons/ember-bootstrap/pull/43) PR.
