### ISSUE TITLE
issue with bundle exec rake

### ISSUE THREAD

**Issue by ghost** [emberjs-addons/ember-bootstrap#45]
How do I fix this? Also, why is a specific v. of rake required? 

<code>
$ bundle exec rake --trace
*\* Invoke default (first_time)
*\* Invoke dist (first_time)
*\* Execute dist
Building Ember Bootstrap...
rake aborted!
cannot load such file -- json
/home/cornihilio/src/b2bcm/ember-bootstrap/Assetfile:2:in `require'
/home/cornihilio/src/b2bcm/ember-bootstrap/Assetfile:2:in`block in rebuild_from_assetfile'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:240:in `instance_eval'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:240:in`block in rebuild_from_assetfile'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/dsl/project_dsl.rb:25:in `instance_eval'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/dsl/project_dsl.rb:25:in`evaluate'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:102:in `build'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:240:in`rebuild_from_assetfile'
/home/cornihilio/.gem/ruby/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:93:in `initialize'
/home/cornihilio/src/b2bcm/ember-bootstrap/Rakefile:9:in`new'
/home/cornihilio/src/b2bcm/ember-bootstrap/Rakefile:9:in `pipeline'
/home/cornihilio/src/b2bcm/ember-bootstrap/Rakefile:67:in`block in <top (required)>'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in`mon_synchronize'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in`mon_synchronize'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block (2 levels) in top_level'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block in top_level'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/cornihilio/.gem/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/home/cornihilio/bin/rake:23:in `load'
/home/cornihilio/bin/rake:23:in`<main>'
Tasks: TOP => default => dist

</code>

**Comment by dmathieu** [comment]
What is your version of ruby ?

**Comment by ghost** [comment]
ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-linux]

**Comment by dmathieu** [comment]
@cornihilio: could you pull my latest commits and confirm it fixes the problem on your machine ?

**Comment by rasjones** [comment]
doesn't fix the problem. here's my error.

*\* Invoke default (first_time)
*\* Invoke dist (first_time)
*\* Execute dist
Building Ember Bootstrap...
rake aborted!
undefined method `close' for nil:NilClass
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/file_wrapper.rb:132:in`ensure in create'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/file_wrapper.rb:133:in `create'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/filter.rb:202:in`block (2 levels) in generate_rake_tasks'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:205:in`block in execute'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:200:in`execute'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:144:in`invoke'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline.rb:304:in `block (2 levels) in invoke'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline.rb:304:in`each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline.rb:304:in `block in invoke'
<internal:prelude>:10:in`synchronize'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline.rb:298:in `invoke'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:110:in`each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/rake-pipeline-9008ba072c7a/lib/rake-pipeline/project.rb:110:in `invoke'
/Users/uenyioha/code/projects/ember-bootstrap/Rakefile:67:in`block in <top (required)>'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:205:in`block in execute'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:200:in`execute'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:176:in`block in invoke_prerequisites'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:174:in `each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:174:in`invoke_prerequisites'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/task.rb:144:in`invoke'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:94:in`block (2 levels) in top_level'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:94:in`block in top_level'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:88:in`top_level'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling'
/usr/local/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/usr/local/Cellar/ruby/1.9.3-p327/bin/rake:32:in`<main>'

**Comment by rasjones** [comment]
Never mind. It was my error.

**Comment by dmathieu** [comment]
Good. Thank you.
