### ISSUE TITLE
Support 'disabled' for form fields

### ISSUE THREAD

**Issue by yossi-shasho** [emberjs-addons/ember-bootstrap#46]
Is it possible to add support for 'disabled' attribute of the form fields? other supported HTML attributes would be nice as well, e.g. 'title'

**Comment by dmathieu** [comment]
Yes, this is possible. Would you care to do a pull request ?

**Comment by bradleypriest** [comment]
`disabled` should be supported already, see https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/mixins/text_support.js#L7. What issue are you running into?

**Comment by yossi-shasho** [comment]
It's actually not working. I'm trying to use it like this:

``` handlebars
{{view Bootstrap.Forms.Select   
    valueBinding="..."
    contentBinding="..."
    selectionBinding="..."
    label="..."
    disabled="true"
}}
```

And like this

``` handlebars
{{view Bootstrap.Forms.Select   
    valueBinding="..."
    contentBinding="..."
    selectionBinding="..."
    label="..."
    disabled="disabled"
}}
```

And none seem to work

**Comment by bradleypriest** [comment]
Ahh, good catch, it looks like the `disabled` attribute was recently added to Ember.Select emberjs/ember.js#1484.
