### ISSUE TITLE
Add support for button groups

### ISSUE THREAD

**Issue by extesy** [emberjs-addons/ember-bootstrap#47]
One particular UI element is missing - button groups:

```
<div class="btn-group" data-toggle="buttons-radio">
  <button id="score20" class="team2score btn btn-small">0</button>
  <button id="score21" class="team2score btn btn-small">1</button>
  <button id="score22" class="team2score btn btn-small">2</button>
  <button id="score23" class="team2score btn btn-small">3</button>
  <button id="score24" class="team2score btn btn-small">4</button>
  <button id="score25" class="team2score btn btn-small">5</button>
</div>
```

I should support both "buttons-checkbox" and "buttons-radio" toggle styles.

**Comment by dmathieu** [comment]
I don't think btn-group would be a good addition. It is only an html tag, which has no use for any binding attribute.
And adding all the buttons programmatically would make it harder to maintain the template.
Just add a div btn-group with all your buttons around it.

**Comment by extesy** [comment]
@dmathieu But it does have a useful binding: selected button! I would rather use one control with a single-variable binding than do jquery magic to figure out which of the buttons from the group is selected. It's actually quite similar to the dropdown list with options in this sense.

**Comment by dmathieu** [comment]
I don't see any change, visible nor in the dom in the bootstrap documentation for the selected button in [btn-group](http://twitter.github.com/bootstrap/components.html#buttonGroups).

Anyway, selected button or not, the problem remains the same. This would be one very big handlebars helper with a lot of parameters in it, which would be very hardly usable.

**Comment by extesy** [comment]
Selected button has 'active' class added to it. Why should the helper be big? How is list of buttons in div tag different from list of options in select tag?

**Comment by dmathieu** [comment]
Buttons are components by themselves.
They need to have bindable attributes, and possibly change the current route when clicking on them.

An option in a select tag is only an array entry, which doesn't behaves as a component by itself. It exists only because it is wrapped around a select tag, which controls it.

**Comment by extesy** [comment]
Yes, that's true, but I think it's ok to not support the full button's functionality for each individual button in a group. Some helper is better than no helper and the ability to bind to the currently selected button(s) is very useful in itself.

**Comment by diosney** [comment]
@dmathieu : Hi, navigation bars are in this category too? I mean: are too complex of implement or otherwise they can be implemented in another way?

Can be used a mix of ember-bootstrap and twitter-bootstrap.js itself in the same project?

**Comment by dmathieu** [comment]
@diosney: I think navigation bars could be implemented. And yes ember bootstrap and the native twitter bootstrap libraries can be used together.
Note : for the purpose of readability, it would be better to open a new ticket for new requests/issues.

**Comment by diosney** [comment]
Sure, I will file a new issue with the navigation request.

Thanks.

**Comment by dmathieu** [comment]
Hmm, I read progress bar, foolish me.
In fact, navbars have somewhat the same problem as button groups.

Look at [modalPane](https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/views/modal_pane.js) for example.
It exists, but the buttons are currently having only the default bootstrap behavior. We can't use the router on them.
The problem with those groups is the same.

**Comment by diosney** [comment]
Oh! I see. Thanks anyway, I will close the issue then referencing this one.

**Comment by dmathieu** [comment]
Closing this one too. If you have an implementation to propose, please open a pull request.
