### ISSUE TITLE
Binding bug @ Pills and Stacked Pills?

### ISSUE THREAD

**Issue by maerten** [emberjs-addons/ember-bootstrap#5]
Hi! 

I just noticed that clicking the A, B, & C pills causes the stacked pills to update with the same selection. But when I go back to clicking pill 'B' and then 'A' again, the stacked pills are stuck at selecting pill 'B'.
Similar things happen when clicking the stacked pills, the normal pills above seem to update only when clicking stacked pill 'C' and 'A'.

I'm using the newest Safari on OS X 10.7.3.

Thanks for creating ember-bootstrap!

**Comment by jzajpt** [comment]
Thanks for noticing, I've been working on stuff related to item selection and it should be OK now.
