### ISSUE TITLE
bindingContext is now removed

### ISSUE THREAD

**Issue by ferdy-lw** [emberjs-addons/ember-bootstrap#50]
As of https://github.com/emberjs/ember.js/commit/4df1d40e5b650fa20c598b36f5da14e7ab2aa5e9 the bindingContext does not exist anymore which means the errors will not work with Form Fields.  If you use an ember release after that commit you'll have to change the `bindingContext` to `context` in the errorsView of Bootstrap.Forms.Field (and update any code that used to directly bind bindingContext to something).

I started with a pull request with this change but there are some other (failing tests) issues when running against the latest ember which I have not fixed yet.

I'm also holding back because I think this is likely to be a non backward compatible change, you'll have to upgrade to the latest ember to use this bootstrap.

**Comment by dmathieu** [comment]
Sorry for the delay. Yes, we're late on the support of the latest versions of ember.
See also #56
