### ISSUE TITLE
DatePicker and TimePicker addition

### ISSUE THREAD

**Issue by fvisticot** [emberjs-addons/ember-bootstrap#53]
I would like to use the DatePicker and TimePicker
from:
https://github.com/jdewit/bootstrap-timepicker
https://github.com/eternicode/bootstrap-datepicker

Can you please provide support to get those 2 components part of this framework ?

**Comment by dmathieu** [comment]
This library isn't meant for hosting all bits of code around twitter bootstrap.
There are many datepickers, for twitter bootstrap or not. And you can also create your own (and open source it if you wish).

Take a look for example, at [this one](https://gist.github.com/1957492), built for [jquery UI's datepicker](http://jqueryui.com/datepicker/)
