### ISSUE TITLE
building fails with invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by mreinsch** [emberjs-addons/ember-bootstrap#55]
$ rake
Building Ember Bootstrap...
rake aborted!
"\xC3" on US-ASCII

$ rake --trace
*\* Invoke default (first_time)
*\* Invoke dist (first_time)
*\* Execute dist
Building Ember Bootstrap...
rake aborted!
invalid byte sequence in US-ASCII
/Users/mr/Projects/3rdparty/ember-bootstrap/Assetfile:9:in `gsub!'
/Users/mr/Projects/3rdparty/ember-bootstrap/Assetfile:9:in`block in generate_output'
/Users/mr/Projects/3rdparty/ember-bootstrap/Assetfile:7:in `each'
/Users/mr/Projects/3rdparty/ember-bootstrap/Assetfile:7:in`generate_output'

**Comment by bradleypriest** [comment]
What version of rake are you using?

**Comment by mreinsch** [comment]
$ rake --version
rake, version 0.9.2.2

That is in the Gemfile.lock

**Comment by dmathieu** [comment]
And what version of ruby are you using ? I just tried with 1.9.3-p194 and it works fine.

**Comment by mreinsch** [comment]
I'm using ruby-1.9.3-p327. Sorry for not including those details initially, I assumed this to be more straight forward issue...

Anyway, looking into this more deeply, I noticed that after running rake ~3 times it then finally runs without the exception. But after removing the tmp directory, the exception appears again. @dmathieu, did you remove the tmp directory before running rake?

Thanks!
