### ISSUE TITLE
EmberJS pre3 compatibility

### ISSUE THREAD

**Issue by sanfords** [emberjs-addons/ember-bootstrap#56]
I'm having some build issues with EmberJS Pre3.

http://localhost:9292/tests/index.html?package=ember-bootstrap reports:

Tests completed in 1642 milliseconds.
279 tests of 287 passed, 8 failed.

Safari 6.0.2, 10.8.2.

**Comment by dmathieu** [comment]
Yes, we are a bit late on the support of the latest versions.
If you want to start working on this, we gladly accept pull requests.

**Comment by dmathieu** [comment]
I have just pushed three commits bringing compatibility with the latest ember (and breaking it with older versions).
Feel free to try it.

**Comment by sanfords** [comment]
Thank you!
