### ISSUE TITLE
Support for required, rows, cols, placeholder, disabled, maxlength 

### ISSUE THREAD

**Issue by devilankur18** [emberjs-addons/ember-bootstrap#66]
Ember default TextField provide a support to a lot of html attributes
http://emberjs.com/api/classes/Ember.TextArea.html

I was trying the required html attribute

```
{{view Bootstrap.Forms.TextField valueBinding="name" label="Name" help="Name of the project" required="true" }}
```

If the fields is empty it should show the error mentioning that this field is required. Like this provide it 

```
<div class="control-group">
  <label class="control-label" for="name">Name</label>
  <div class="controls">
    {{view Ember.TextField valueBinding="name" id="name" placeholder="Name" required="true"}}
  </div>
</div>
```

**Comment by dmathieu** [comment]
rows and cols [are already available](https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/forms/text_area.js#L7).
For the other fields, please feel free to open a pull request adding them.

**Comment by bradleypriest** [comment]
Check out [Bootstrap.Forms.TextField](https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/forms/text_field.js), [Bootstrap.Forms.TextArea](https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/forms/text_area.js) and the shared [Bootstrap.Forms.TextSupport](https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/lib/mixins/text_support.js).

If there are attributes missing there that Ember provides please submit a PR.

If you check the documentation you've linked, `required` isn't available by default on an Ember.TextArea, they're actually showing you how to add it using `attributeBindings`. 

The best way for you to add `required` to your inputs requires reopening Bootstrap.TextSupport and Ember.TextSupport.

``` js
Ember.TextSupport.reopen({
  attributeBindings: ["required"]
})

Bootstrap.TextSupport.reopen({
  requiredBinding: "parentView.required"
})
```

**Comment by devilankur18** [comment]
@bradleypriest Thanks, it worked perfectly.
