### ISSUE TITLE
Add ember-bootstrap to bower registry

### ISSUE THREAD

**Issue by fayimora** [emberjs-addons/ember-bootstrap#70]
I think it will be nice to have this added to the "bower registry". What do you think?

**Comment by AyKarsi** [comment]
It appears to be on bower registry now. So I think this issue can be closed

**Comment by dmathieu** [comment]
How do you see that ? What version is on the bower registry ? Who maintains it ?

**Comment by AyKarsi** [comment]
I just ran bower search ember from the console and i would have thought that you must have done it.. 

this is the bower.json I'm getting:

```
{
  "name": "ember-bootstrap",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": "git://github.com/emberjs-addons/ember-bootstrap.git"
  }
}
```

**Comment by dmathieu** [comment]
Still no idea who submitted this. And the bower doc about packages isn't very clear on how to send updates.
From what I seem to understand, the package is automatically updated when a tag is created on the git repository ?

I'm closing this issue, as it doesn't seem to be a problem anymore for now.

**Comment by fayimora** [comment]
Yes I think the bower registry automatically updates itself when a new tag gets created...

**Comment by dmathieu** [comment]
Awesome.
FYI, the 0.0.1 version is pretty old and I wouldn't recommand using it.
We will release 1.0.0 with the stable release of emberjs 1.0.0.

**Comment by fayimora** [comment]
Cool thanks
