### ISSUE TITLE
navlist bind to model

### ISSUE THREAD

**Issue by benmonro** [emberjs-addons/ember-bootstrap#73]
I'd like to bind a Navlist to a model rather than a controller, so that the list of items in my model can show up as a navlist... any ideas?

**Comment by dmathieu** [comment]
I would still bind the items to the controller.
And, in your controller, get your content from the model.

```
App.NavController = Ember.ObjectController.extend({
  content: function() {
    App.NavModel.find(1)
  }.property()
});
```
