### ISSUE TITLE
Alert Message not working

### ISSUE THREAD

**Issue by flynfish** [emberjs-addons/ember-bootstrap#75]
Hi, I'm new to ember so I'm not sure if I am doing something wrong or not. When using the alert message and clicking the close link, the click event is not being caught by the view and therefore the message doesn't close. 

Ember.VERSION : 1.0.0-rc.3
Handlebars.VERSION : 1.0.0-rc.4

```
Bootstrap.AlertMessage.create({
   type: "error",
   message: "Error!"
}).append();
```

I also tried updating the template link with the action helper but that didn't change anything:

```
template: Ember.Handlebars.compile('<a {{action click this target="view"}} class="close" rel="close" href="#">&times;</a>{{{view.message}}}'),
```

Any ideas if it's a bug or something I am doing wrong?

**Comment by dmathieu** [comment]
The test suite is broken on 1.0.0-rc.4. I presume it is on rc.3 too.
I'm getting errors `calling set on destroyed object` whenever calling `#destroy` on an element appended to the DOM.

**Comment by bradleypriest** [comment]
I'm pretty sure using `append()` adds the DOM outside of the Ember Application, so therefore event handling will not be managed correctly. I've never used the AlertMessage myself though

**Comment by dmathieu** [comment]
The problem occurs on all elements in rc.4. Not only AlertMessage.

**Comment by dmathieu** [comment]
The tests are now fully passing on rc.6. Your bug shoud be fixed.
