### ISSUE TITLE
Button Group is not supported

### ISSUE THREAD

**Issue by flynfish** [emberjs-addons/ember-bootstrap#76]
According to the example page http://emberjs-addons.github.com/ember-bootstrap/ there should be a RadioButtonGroup view, but it doesn't exist in the code. 

There was discussion in #47 about this.

**Comment by dmathieu** [comment]
Hey, Thank you for the suggestion. I'm going to close this issue, for the same reason as the previous one was closed.
Issues aren't meant for feature requests, but for bugs. If you want button groups, I'd be glad to merge a pull request.

**Comment by flynfish** [comment]
It was more of a bug report in that the example website shows a RadioButtonGroup, but that view doesn't exist which make it confusing for folks when they try to implement it. Can the RadioButtonGroup example be removed to avoid the confusion?

I will look into making a PR.

**Comment by dmathieu** [comment]
The example website is not really up to date, as it's not been maintained for quite some time.
