### ISSUE TITLE
Compiled files

### ISSUE THREAD

**Issue by Y-Less** [emberjs-addons/ember-bootstrap#77]
Can you not provide compiled files within the repository?  Just to use this I've had to install Ruby, then wade through errors about:

1) Requiring 1.9, not the 1.8 I apparently had by default.
2) Fix errors about not finding "mkmf" (apparently to do with needing ruby1.9.1-dev not just ruby1.9.1).
3) Figure out why "rake" wouldn't run at all.
4) Learn what gems are, then install them.
5) Instally libxml2-dev, libxslt-dev (the requirement on which weren't clear).

Plus fix a few other errors just to run one program once to compile this code...

**Comment by Y-Less** [comment]
In the end I had to add this line to the gemfile to get it to build:

```
gem "therubyracer", :require => 'v8'
```

Without that it complained about:

```
Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
```

Despite the fact that I had JUST installed it!

**Comment by dmathieu** [comment]
We're now using the official [ember-dev](https://github.com/emberjs/ember-dev) build tools. This should make it easier for you to build.

**Comment by dmathieu** [comment]
Oh, and there is a release with the compiled packages.
https://github.com/emberjs-addons/ember-bootstrap/releases/v0.0.2

**Comment by Y-Less** [comment]
Awesome, thanks.
