### ISSUE TITLE
how to use typeAhead？

### ISSUE THREAD

**Issue by seagod** [emberjs-addons/ember-bootstrap#83]
i use the

```
{{view App.Bootstrap.TypeAhead valueBinding="assistantForInputQ" class="input-medium" url="userinfomanage_getUserName.action" idProperty="name"}}
```

in page...

and return the result as `[{ name: 'Terry'}, { name: 'Mark'}, {  name: 'Jacob'}]...`

the error like this..

> Uncaught TypeError: Cannot use 'in' operator to search for '53' in [{ name: 'Terry'}, { name: 'Mark'}, {  name: 'Jacob'}] 

even i return `[ 'Terry',   'Mark',   'Jacob']`  the error is ever exist .

so pls tell me  return what result for typeahead....pls.

**Comment by dmathieu** [comment]
There is no `TypeAhead` in this library ... Are you sure you're not using a component internal to your app ?

**Comment by seagod** [comment]
oh...
