### ISSUE TITLE
ISO8601Date is not defined 

### ISSUE THREAD

**Issue by webhive** [emberjs-addons/ember-bootstrap#91]
Most of code related to ISO8601Date seems commented but single reference to this function still exists and caused an error if using Bootstrap.DatePicker

**Comment by dmathieu** [comment]
There isn't any DatePicker in this library, nor any usage of any ISO8601 method ...

**Comment by webhive** [comment]
Sorry - it was https://github.com/pjlammertyn/ember-bootstrap
Just got this issue again :(

Hmmm this guy https://github.com/pjlammertyn/ember-bootstrap added reference to your issue tracker, so all the issues going to you - this is why I posted it to you.
