### ISSUE TITLE
no such file to load -- bundler/setup

### ISSUE THREAD

**Issue by yankeeinlondon** [emberjs-addons/ember-bootstrap#94]
Sorry to be such a Ruby noob but when I download your repo and run `rake` I get the following error: `no such file to load -- bundler/setup`. I'm guessing there's a dependency i'm missing that may be obvious to a Ruby person but I'm missing the trick.

**Comment by dmathieu** [comment]
You need to install bundler.

```
gem install bundler
```

But you also don't need ruby. You can just use the latest build, available in [the releases](https://github.com/emberjs-addons/ember-bootstrap/releases).
