### ISSUE TITLE
Add dist folder to repo?

### ISSUE THREAD

**Issue by flynfish** [emberjs-addons/ember-bootstrap#98]
Would it be possible to add the dist build folder/files to the repo so we can grab the js files without cloning the project and running rake?

**Comment by dmathieu** [comment]
You can do that with the official releases already.
https://github.com/emberjs-addons/ember-bootstrap/releases

**Comment by flynfish** [comment]
@dmathieu oh sweet, somehow I never saw that! Thanks.

**Comment by flynfish** [comment]
@dmathieu Any chance you can add a release from this commit, which is the last before the bootstrap 3 changes starting going into master?

https://github.com/emberjs-addons/ember-bootstrap/commit/209f2d5c459cb87c767cd343447a2803a8f4da11

**Comment by dmathieu** [comment]
Unfortunately, I would rather not. I can only release upper versions, not add ones in the middle.
So this would mean I'd have to release 0.0.4 with your commit, which would definitely confuse anyone coming afterwards.
